### ISSUE TITLE
Build script is failing 

### ISSUE THREAD

**Issue by yaswanth16** [open-abap/azure-functions-v4-abap-template#6]
![image](https://user-images.githubusercontent.com/29703852/206863799-774a3781-8df7-49c2-92fc-47b09229f719.png)

Build step is failing to generate the js files and the output folder. It simply exits with this log. Am I missing something here?? I did install all @abaplint packages in global as well. Installed all the required ABAP extensions for VS Code.

**Comment by yaswanth16** [comment]
FYI. Thought that this might an issue with my system setup. Tried replicating with a Github Codespace and encountered the same error. 

![image](https://user-images.githubusercontent.com/29703852/206908535-be9379ac-8667-4177-a5b5-36fcac761bc3.png)

**Comment by larshp** [comment]
try again, I've updated the dependencies to latest, https://github.com/open-abap/azure-functions-v4-abap-template/pull/7

**Comment by yaswanth16** [comment]
Thanks @larshp . The flow seems to work now.

But I have one last question. The build folder contains all the global types, data elements, exception classes etc...Is there a way we can generate only the necessary global artifacts? I don't have the full understanding of the abap transpiler , but can we use the syntax trees during the parse phase to restrict the list of generated artifacts ??

**Comment by larshp** [comment]
https://github.com/open-abap/azure-functions-v4-abap-template/blob/main/abap_transpile.json#L5 defines which stuff to pull in, you can define any repository there

there is no "tree shaking" implemented as of now, but would be a nice feature

**Comment by larshp** [comment]
also see https://open-abap.org, I will be reducing the number of objects in "core", just takes time...

**Comment by yaswanth16** [comment]
Awesome....BTW I genuinely appreciate the work you and others from ABAP community are doing.

I wish to contribute to these topics....I can see lot of topics related to open abap, abaplint, etc.. scattered over different repos...I will scour them for beginner issues first and start contributing....Any beginner guide/links would be very helpful 👍👍👍
